version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres-movies
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: moviesdb
    ports:
      - 5432:5432
    volumes:
      - ../.data/postgres/data:/var/lib/postgresql/data
    
  minio:
    image: minio/minio:latest
    container_name: minio-movies
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - ../.data/minio:/data